Страницы
praktikum-beta-team/catcher pull request #2
Opened 2020-08-27 07:04 UTC by 0151

- Авторизация/главная (/)
- Регистрация (/signin)
- Настройки пользователя (/settings)
- Список лидеров (/leaderboard)

Пока без адаптивности

2020-08-28 10:34 UTC, Ortiz1221 requested changes
Спасибо тебе большое, очень круто =) Добавила несколько комментариев, где можно было бы  немного поправить.

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Modal/Modal.scss
> +    margin-bottom: 108px;
:exclamation: Нам точно нужно настолько большое расстояние? Сначала подумала, что там картинка не подгрузилась. Если нет планов что-то вставлять туда, предлагаю всё таки сделать поменьше. 40px, например.

![image](https://user-images.githubusercontent.com/41075682/91546394-0a116880-e92b-11ea-9e50-a5a32bd6364c.png)
![image](https://user-images.githubusercontent.com/41075682/91546577-58266c00-e92b-11ea-910e-82abe31d5d4d.png)

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Button/Button.scss
> +    /* Плоская, без фона и границ */
❓ Не уверена, что здесь нужны комментарии. Вроде из названий и значений и так понятно что там происходит. Ну а модификатор говорит, что это изменения внешности кнопки.

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Signin/Signin.tsx
> +          <div className="ford-field">
❗ 
```suggestion
          <div className="form-field">
```

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Button/Button.scss
> +    &_pseudo {
❓ Не смогла воспроизвести у себя навешивание этого модификатора. Что именно он должен делать?

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Signup/Signup.tsx
> +          <div className="ford-field">
❗ 
```suggestion
          <div className="form-field">
```

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Signin/Signin.scss
> +  background-size: cover;
❗ Эта часть дублируется в Signup.scss. Предлагаю подумать как тут можно использовать, например, директиву @extend (в доках sass - это блок про расширение/наследование)

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Input/Input.scss
> +      padding-bottom: 0;
❗ Дублирует код ниже в `&_invalid .input__control`. Может в миксин вынести?

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Header/Header.scss
> +  border-style: solid;
❗ Дублирует код (в Input.scss в `input__control` и в Leaderboard.scss `.board`). Может вынести в миксин либо наследование (через % и @extend).

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Signin/Signin.scss
> +    background-color: #222;
❗ Тут хорошо бы тоже вынести в переменную

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/AvatarInput/AvatarInput.scss
> +  background-color: rgba(0, 0, 0, 0.45);
❗ Может в переменную это?

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/AvatarInput/AvatarInput.scss
> +  justify-content: center;
❗ По стилям пару раз встречала это и `display: flex;`. Может вынести это все в миксин, например?

2020-08-28 10:34 UTC, Ortiz1221 commented on src/components/Avatar/Avatar.tsx
> +  const cn = createCn("avatar");
❓ Не настаиваю, но может переименовать на что-то более очевидное?

2020-08-29 08:42 UTC, 0151 commented on src/components/Button/Button.scss
> +    &_pseudo {
Меняет стиль кнопки, пример - "Зарегистрироваться" на главной.

2020-08-29 14:26 UTC, Ortiz1221 approved these changes

2020-09-02 13:59 UTC, aleksandr-yakovlev approved these changes
Круто, особенно навыки css/scss впечатлили!

2020-09-02 13:59 UTC, aleksandr-yakovlev commented on src/components/Avatar/Avatar.tsx
> +export const Avatar: FC<IAvatarProps & HTMLAttributes<HTMLDivElement>> = (props) => {
:question:  Предлагаю вынести все переиспользуемые компоненты в src/ui

2020-09-02 13:59 UTC, aleksandr-yakovlev commented on src/components/AvatarInput/AvatarInput.tsx
> +  const handleClick = (): void => {
Кажется тут должны быть пропсы

2020-09-02 13:59 UTC, aleksandr-yakovlev commented on src/components/Settings/Settings.tsx
> +                <div className="form-field">
:question: Бросается в глаза дублирование <div className="form-field">. Может стоит объект заиспользовать и потом циклом построить? Или для дивов назначить единый класc?

2020-09-02 19:09 UTC, ShevchenkoAlexen requested changes
Привет! 
В целом все все очень даже ничего. По css все хорошо, но местами неоправданно сложно. По js - грязновато. Если используем createCn("") - то надо использовать везде. Все что можно вынести из функции - все надо вынести. Если в css есть отдельные компоненты, то они должны быть и в js отдельными, и в файловой системе.

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Avatar/Avatar.tsx
> +  const cn = createCn("avatar");
❗ Лучше вынести константу из функции

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Avatar/Avatar.tsx
> +  const avatarClassName = cn({ size }) + (className ? ` ${className}` : "");
Можно сделать хелпер, который будет делать join

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/AvatarInput/AvatarInput.scss
> +  content: "Изменить\0aфото\0aпрофиля";
❗ Не лучшее решение хранить текст в стилях. В больших проектах обычно несколько языков. Лучше вынести в js и в константы

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/AvatarInput/AvatarInput.tsx
> +  const handleClick = (): void => {
ЛУчше еще заиспользовать useCallback

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Leaderboard.tsx
> +  const boardEntries = mockData.map((entry, index) => (
Тут можно использовать hook, чтобы  предотвращать повторные отрисовки

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Avatar/Avatar.tsx
> +  const cn = createCn("avatar", className);
❗ Если вынести константу за пределы функции, то она не будет пересоздаваться каждый раз.

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Avatar/Avatar.tsx
> +      {src && <img className="avatar__image" src={src} alt={alt} />}
❓ Может быть добавить значение по-умолчанию у src

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/AvatarInput/AvatarInput.scss
> +  $hover-text: "Изменить\0aфото\0aпрофиля";
❗ Это плохая идея добавлять текст внутрь css. Текст меняется, например при смене языка. 
Обычно либо используются внешние системы с текстами, которые могут править контент менеджеры, либо выносятся в отдельный js и вставляются через js
пока это выглядит как хак

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/AvatarInput/AvatarInput.scss
> +  $hover-text: "Изменить\0aфото\0aпрофиля";
Предлагаю сделать 2 слоя, и по ховеру 1 скрывать, или менять местами.

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Button/Button.scss
> +  height: 48px;
Кажется тут есть свойства, без которых можно обойтись
![image](https://user-images.githubusercontent.com/31590450/92023112-f4ee6c80-ed64-11ea-8d9d-bfff224c9132.png)

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Form/Form.scss
> +.form-field {
❗ Кажется, это должно быть в отдельной компоненте

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Form/Form.tsx
> +  <form {...restFormProps}>
❓ А где import { createCn } from "bem-react-classname";
+ у тега форм надо бы добавить classname

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Input/Input.tsx
> +      <input className="input__control" {...restInputProps} />
❗ cn вынести в константы, использовать cn

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Input/Input.tsx
> +    <div className={cn({ invalid: !!error })}>
Boolean(error)

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Entry/Entry.tsx
> +    <td className="board__cell">{place}</td>
❗ Тут забыл const cn = createCn("");

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Entry/Entry.tsx
> +    <td className="board__cell">{place}</td>
+ сразу бы на вход получить массив результатов

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Leaderboard.scss
> +.board {
❗ В 1 css должны быть стили для 1 компоненты

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Leaderboard.tsx
> +            <table className="board">
С этой компонентой надо поработать, но наверно пока можно оставить

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Leaderboard.tsx
> +      <div className="leaderboard">
const cn = createCn("");

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Modal/Modal.tsx
> +  <div className="modal">
const cn = createCn("input");

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Settings/Settings.scss
> +.settings-form {
❗ Тут тоже надо вынести в отдельную компоненту

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Settings/Settings.tsx
> +      <div className="settings">
const cn = createCn("input");

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Settings/Settings.tsx
> +            <Form className="settings-form">
я бы тут  тоже сделал компоненту  Form, но добавил бы компоненту FormField
А все вместе, обернул в SettingsForm
В остальных формах все то же самое

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Signin/Signin.tsx
> +        <Form>
const cn = createCn("input");

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Signup/Signup.tsx
> +    <div className="signup__wrapper">
const cn = createCn("input");

2020-09-02 19:09 UTC, ShevchenkoAlexen commented on src/components/Signup/Signup.tsx
> +            <Button view="action">Зарегистрироваться</Button>
Текста лучше выносить в константы, чтобы можно было бы править все в одном месте

2020-09-05 15:42 UTC, 0151 commented on src/components/AvatarInput/AvatarInput.tsx
> +  const handleClick = (): void => {
Не совсем понял, как и где использовать useCallback

2020-09-05 16:32 UTC, Ortiz1221 approved these changes

2020-09-05 19:15 UTC, ShevchenkoAlexen commented on src/components/Avatar/Avatar.tsx
> +const cnAvatar = cn("avatar");
специфичные названия тут лучше не придумывать. У нас в проектах везде называется b или b_ от слова block

2020-09-05 19:15 UTC, ShevchenkoAlexen commented on src/components/Signin/Signin.tsx
> +import { SigninForm as Form } from "components/SigninForm";
❓ А зачем переименовывать?

2020-09-05 19:15 UTC, ShevchenkoAlexen commented on src/components/UI/Avatar/Avatar.tsx
> +      role="img"
🔥

2020-09-05 19:15 UTC, ShevchenkoAlexen commented on src/components/UI/AvatarInput/AvatarInput.tsx
> +  const handleClick = (): void => {
🔥

2020-09-05 19:20 UTC, ShevchenkoAlexen commented on src/components/AvatarInput/AvatarInput.tsx
> +  const handleClick = (): void => {
Привет! по этому поводу есть статья https://habr.com/ru/company/hh/blog/439138/

Если кратко, то при каждом вызове компонента AvatarInput будет создана новая функция handleClick
Чтобы этого избежать - следует использовать useCallback

2020-09-05 20:07 UTC, 0151 commented on src/components/Avatar/Avatar.tsx
> +const cnAvatar = cn("avatar");
Я подсмотрел именование в [Yandex UI Kit](https://github.com/bem/yandex-ui/blob/952662a573a3d35b14eea5ff8c525ad565b476ed/src/components/Button/Button.tsx#L158)

2020-09-07 04:56 UTC, ShevchenkoAlexen commented on src/components/Avatar/Avatar.tsx
> +const cnAvatar = cn("avatar");
Источник авторитетный, это не крит, это скорее элемент кодстайла. Который вам необходимо решить в команде.

2020-09-07 05:19 UTC, ShevchenkoAlexen commented on src/components/Settings/Settings.tsx
> +      <div className={cnSettings("wrapper")}>
Кажется, минимум 1 div тут лишний, может быть можно обойтись без него?

2020-09-07 05:19 UTC, ShevchenkoAlexen commented on src/hooks/useForm.ts
> +  const handleSubmit = (callback?: (data: T) => void) => (event: FormEvent<HTMLFormElement>) => {
🔥

2020-09-08 09:14 UTC, ShevchenkoAlexen approved these changes

2020-09-08 09:14 UTC, ShevchenkoAlexen commented on src/components/Settings/Settings.tsx
> +    <div className={cnSettings("wrapper")}>
Осталось убрать слово wrapper, и будет вообще огонь

2020-09-08 09:18 UTC, ShevchenkoAlexen approved these changes

2020-09-08 09:18 UTC, ShevchenkoAlexen commented on src/components/Leaderboard/Leaderboard.tsx
> +      <div className={cnLeaderboard()}>
тут тоже div лишний

2020-09-08 09:18 UTC, ShevchenkoAlexen commented on src/components/Settings/Settings.scss
> +  &__wrapper {
зачем использовать wrapper если settings пустой ?

2020-09-08 09:18 UTC, ShevchenkoAlexen commented on src/components/Signup/Signup.scss
> +  &__wrapper {
❓ зачем тут wrapper ? стили можно перенести в signup

2020-09-09 10:20 UTC, aleksandr-yakovlev approved these changes
ok

2020-09-09 13:56 UTC, 0151 commented on src/components/Signup/Signup.scss
> +  &__wrapper {
Почистил везде

2020-09-09 14:13 UTC, merged