Первый спринт
praktikum-beta-team/catcher pull request #6
Opened 2020-09-16 12:47 UTC by 0151

Концепция, бойлерплейт, роутинг, основные страницы, утилита для работы с API

2020-09-21 12:12 UTC, noveogroup-amorgunov requested changes
Очень качественный ПР, вы большие молодцы! За тесты и README отдельный лукас.

В своих сообщениях я использовал следующую нотацию:

(!) Нужно исправить или привести аргументы против исправления
(?) Рассказать, почему сделано именно так или поправить на предложенный вариант
(пусто) Рекомендация от меня, желательно поправить, но можно оставить и в текущем виде

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on default.conf.template
> +}
Все файлы, связанные с docker-ом лучше помещать в директорию `docker`, чтобы они не перемешивались с файлами проекта

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on package.json
> +    "react-router-dom": "^5.2.0"
Сейчас у зависимостей проставлен крыжек (^) - при их установки, патч-версия библиотеки будет обновляться, что в некоторых кейсах может сломать проект. Поэтому мы в своих проектах устанавливают зависимости без ^, чтобы зафиксировать версию (можно создать файл `.npmrc` и добавить туда строчку save-exact=true), а в package.json вручную удалить ^

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on package.json
> +    "sass-loader": "9.0.3",
(?) При использовании postcss необходимость в sass отпадает, для чего его установили? sass при установке зависимостей компилируется из исходников на питоне, что увеличивает время сборки, поэтому предлагаю выпилить его из проекта.

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on package.json
> +      "pre-commit": "npm run test && npm run lint:all"
На каждый коммит запускать тесты (которых со временем может стать много) - это конечно же круто, но довольно долго. Предлагаю добавить опцию `pre-push` и только на пуш запускать тесты

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/App/App.test.tsx
> +  test("should display app component", async () => {
(?) Зачем async ?

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/App/App.tsx
> +export const App: FC = () => (
Мой совет: не стоит явно указывать возвращаемый тип (в функциональных компонентах и в методах render классовых компонент), так как TS сам это понимает и выводит тип. Да и код будет короче. Возвращаемый тип указывать только в интерфейсах и типах.

Если решите указывать тип возвращаемых функций, то указывать стоит везде

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/App/App.tsx
> +import { ErrorBoundary } from "components/ErrorBoundary";
Кажется это не просто компоненты, а полноценные страницы, их удобнее положить в отдельную директорию pages, отдельно от обычных компонентов

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/App/App.tsx
> +import { ErrorBoundary } from "components/ErrorBoundary";
Очень удобно создавать components/index.ts файл, в который импортировать все компоненты и сразу экспортировать их. Данный код можно было бы переписать как-то так:

```tsx
import { Signin, Signup, Settings, Leaderboard } from "pages";
import { ErrorBoundary } from "components/ErrorBoundary";
```

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/App/App.tsx
> +      </Route>
(?) А разве нельзя в ErrorBoundary обернуть все приложение, а не каждый route по отдельности?

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/App/App.tsx
> +      </Route>
Здесь много повторяющегося кода, правильнее сделать массив роутов (с path и component) и в цикле их рендерить

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on www/index.html
> +<!DOCTYPE html>
Думаю нет смысла создавать отдельный каталог для одного файла. Его можно положить в src

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on webpack.config.js
> +    new MiniCss({ filename: "style.[hash].bundle.css", disable: false, allChunks: true }),
CSS имеет смысл сжимать только для продакшен сборки, при разработке - это только увеличение времени сборки и пересборки

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on webpack.config.js
> +    new MiniCss({ filename: "style.[hash].bundle.css", disable: false, allChunks: true }),
Так же если сжимаете CSS, желательно сжимать и JS

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on webpack.config.js
> +        use: ["ts-loader", "eslint-loader"],
(?) Я правильно помню, что eslint-loader делает так, что при ошибке в коде (пробел лишний или точки с запятой нет) он не собирает проект? Если так, то очень-очень советую это выпилить, так как это замедляет разработку.

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/index.ts
> +export { auth };
(?) Нотация `export { * as auth } from "./auth";` не работает? В других местах используется именно она

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Board/Board.tsx
> +};
(!) Все текста стоит вынести в отдельный файл. Можно заиспользовать какую-нибудь библиотечку, но это уже по желанию

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Board/Board.tsx
> +export const Board: FC<IBoardProps> = (props) => {
Вкусовщина, но код короче и понятнее
```suggestion
export const Board = (props: IBoardProps) => {
```

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  render(): React.ReactNode {
Послендий раз напишу об явном указании типов и больше не буду это упоминать: `:void` выше, `: React.ReactNode` - здесь, это все делает код более похожим на Java, где очень много болерплейт кода.

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +export class ErrorBoundary extends Component {
(!) Состояние как и свойства нужно указывать явно (если оно есть) - `Component<null, IErrorBoundaryState>`

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/ErrorBoundary/ErrorBoundary.test.tsx
> +Enzyme.configure({ adapter: new Adapter() });
(!) Эту строчку нужно проинициализировать один раз при запуске тестов (вместе с import Adapter from "enzyme-adapter-react-16";), а то придется в каждом react-тесте ее прописывать

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Leaderboard/Leaderboard.tsx
> +const cnLeaderboard = cn("leaderboard");
Я на одном из проектов также задавал уникальные названия для стилей. Но это не удобно при копировании компонентов, при их просмотре (так как в каждом будет свое название). Потом мы перешли на именование во всех компонентов одинаково - например `cn_` или `block`, код стал понятнее и чище.

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Leaderboard/mockData.ts
> +export default [
(!) Стоит явно прописать тип данных

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Board/Board.tsx
> +export type BoardEntries = Omit<IBoardEntryProps, "place">[];
Обычно типы называют в единственном числе, например BoardEntry. Везде, где понадобится массив сущностей, просто добавляется []. Скобки сразу позволяют понять, что в переменной массив - это очень удобно.

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Board/Board.tsx
> +export type BoardEntries = Omit<IBoardEntryProps, "place">[];
И чтобы не делать Omit для типа, я бы разделил тип BoardEntry и IBoardEntryProps.

Получилось что-то типа:


```ts
interface IBoardEntry {
  ...
}

interface IBoardEntryProps extends IBoardEntry {
  place: number
}
```

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/Settings/Settings.tsx
> +    <Header />
(!) На всех страницах явно прописывается Header, что не ок. Стоит либо создать Layout, либо просто вынести Header на уровень App.tsx перед роутами

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/SettingsForm/mockData.ts
> +export default {
(!) Указать тип данных

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/SettingsForm/SettingsForm.tsx
> +      <div className="settings-form__column">
Везде используется cn - здесь тоже стоит заиспользовать

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/SettingsForm/SettingsForm.tsx
> +};
```
const initialValues: ISettingsForm = {
  ... mockData
  oldPassword: "",
  newPassword: "",
  newPasswordConfirm: "",
};
```

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/components/UI/Loading/Loading.tsx
> +      {TEXT.LOADING}
Давайте сразу прикрутим какой-нибудь красивый спиннер (например, https://loading.io/css/ или https://projects.lukehaas.me/css-loaders/)

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/request.ts
> +export function request<T>(reqUrl: string, method: Method = "POST") {
В GET запросах T не обязателен, поэтому можно написать вот так `T = unknown`

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/request.ts
> +export function request<T>(reqUrl: string, method: Method = "POST") {
(!) reqUrl стоит заменить на `endpoint` или просто `url`. Префикс req здесь ни к чему

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/auth/user.ts
> +export const user = request<Record<string, unknown>>(AUTH_USER, "GET");
Указав дефолтное значение должно сработать вот так

```ts
export const user = request(AUTH_USER, "GET");
```

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/auth/user.ts
> +export const user = request<Record<string, unknown>>(AUTH_USER, "GET");
Я сейчас понял, что не хватает описания возвращаемого типа, поэтому стоит добавить его в дженерик и использовать вот так:

```
export const user = request<null, IUser>(AUTH_USER, "GET");
```

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/auth/user.test.ts
> +  );
(?) А расскажите как работает от тест? Он же не может проверять сразу две ветки (и 200 и 401). Кажется стоит разбить на два тест кейса

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/auth/user.test.ts
> +  );
(!) И здесь вы же отправляете реальные запросы в API? Их нужно мокать, например с помощью `nock`

2020-09-21 12:12 UTC, noveogroup-amorgunov commented on src/utils/request/auth/models/user.ts
> +};
(!) Пароли и данные стоит убрать из репозитория. Для тестов - мокать запросы, для кода - использовать то, что вводит пользователь

2020-09-22 10:23 UTC, 0151 commented on package.json
> +    "sass-loader": "9.0.3",
Sass уже убрали из проекта

2020-09-22 10:26 UTC, 0151 commented on src/components/App/App.tsx
> +      </Route>
Как сейчас, если будет выброшено исключение, сломается только один роут, а не все приложение

2020-09-22 10:29 UTC, 0151 commented on src/utils/request/index.ts
> +export { auth };
Не работает

2020-09-22 10:30 UTC, 0151 commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +export class ErrorBoundary extends Component {
Если указывать null для пропсов, children получает тип never. Если {}, линтер ругается. Если Record<string, unknown> - компоненту можно будет передать сколько угодно пропсов, тоже не совсем правильно, мне кажется

2020-09-22 14:50 UTC, 0151 commented on src/components/App/App.test.tsx
> +  test("should display app component", async () => {
Поправили

2020-09-24 16:33 UTC, 0151 commented on webpack.config.js
> +    new MiniCss({ filename: "style.[hash].bundle.css", disable: false, allChunks: true }),
MiniCssExtractPlugin сам по себе не сжимает CSS

2020-11-19 08:48 UTC, closed without merging