Feature/services
praktikum-beta-team/catcher pull request #7
Opened 2020-09-25 14:44 UTC by 0151

Добавляет авторизацию, регистрацию и настройки пользователя, использует Redux и Thunk. Исправляет замечания по ПР #6. Пока еще есть нерешенные вопросы с UX, в некоторых случаях по роутам надо переходить вручную: /settings, /leaderboard, /game, /logout

2020-09-29 18:54 UTC, ShevchenkoAlexen requested changes
Привет! На первый взгляд все очень и очень не плохо! Почти не смотрел редакс, завтра еще досмотрю. Так держать, ты на правильном пути.

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/App/App.tsx
> +const routes = componentMap.map(({ component, isPrivate, ...restRouteProps }, index) => {
В целом, это не обязательно. Использовать map. Если бы список генерировался динамически - то да. А так, ничего не мешает сделать список руками. Будет проще и понятнее

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/App/App.tsx
> +export const App: FC = withStartup(() => {
можно использовать сокращенную запись. () => (<Router>....</Router>)

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/Board/Entry/BoardEntry.tsx
>  export const BoardEntry: FC<IBoardEntryProps> = (props) => {
Вообще говоря, не вижу смысла в этой компоненте. Тут же нет никакой логики. Сделать это внутри renderEntries , и даже, наверно, renderEntries не обязательно.
И не будет лишних проблем с циклическими импортами

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/GameScreen/GameScreen.tsx
> +      😼
🔥

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/PrivateRoute/PrivateRoute.tsx
> +  return isAuthenticated ? <Route {...props} /> : <Redirect to="/" />;
👍

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/SettingsAvatar/SettingsAvatar.tsx
> +  const handleChange = () => {
Следует использовать useCallback
https://habr.com/ru/company/hh/blog/439138/

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/SettingsForm/SettingsForm.tsx
> +  const handleSettingsFormSubmit = (values: IUserRequest) => {
тут тоже useCallback

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/SigninForm/SigninForm.tsx
> +  const onSubmit = (values: ISigninRequest) => {
тут тоже useCallback

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/UI/Avatar/Avatar.tsx
> +  return cloneElement(
👍

2020-09-29 18:54 UTC, ShevchenkoAlexen commented on src/components/UI/Layout/Layout.tsx
> +export const Layout: FC = ({ children }) => {
В целом, хотелось бы чтобы стиль компонент сохранялся, а то чередуются коротка и длинная запись стрелочных функций. Без явной причины. Аналогично диструктуризация пропсов то в параметрах функции как тут, то сразу после, без явной разницы.

2020-09-30 08:24 UTC, 0151 commented on src/components/App/App.tsx
> +const routes = componentMap.map(({ component, isPrivate, ...restRouteProps }, index) => {
https://github.com/praktikum-beta-team/catcher/pull/6#discussion_r491954045

2020-09-30 18:58 UTC, Ortiz1221 approved these changes

2020-10-01 07:41 UTC, ShevchenkoAlexen requested changes

2020-10-01 07:41 UTC, ShevchenkoAlexen commented on src/components/App/App.tsx
> +const routes = componentMap.map(({ component, isPrivate, ...restRouteProps }, index) => {
тогда лучше 
`routes.map(({ path, component, isPrivate, ...rest }) => {
  const RouteComponent = isPrivate ? PrivateRoute : Route;
  return (
    <RouteComponent
      key={path}
      path={path}
      component={withErrorBoundary(component)}
      {...rest}
    />
  );
});`
и вставить можно прямо в jsx в app

2020-10-03 18:04 UTC, ShevchenkoAlexen commented on src/components/UI/Form/Form.tsx
> +  error?: null | string;
❓ а зачем тут undefined | null | string  , зачем разделять null и undefined?

2020-10-03 18:04 UTC, ShevchenkoAlexen commented on src/services/auth/selectors.ts
> +    } as IUserRequest)
❓ Кажется тут что-то не то. 
если убрать кастинг типов, то все начинает сыпаться. мб надо обработать этот момент получше?

2020-10-06 17:53 UTC, 0151 commented on src/components/UI/Form/Form.tsx
> +  error?: null | string;
Undefined сейчас не нужен, убрал. Раньше делал проп необязательным.

2020-10-06 17:54 UTC, 0151 commented on src/services/auth/selectors.ts
> +    } as IUserRequest)
Поправил

2020-10-07 13:39 UTC, noveogroup-amorgunov approved these changes
/ok

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on postcss.config.js
> +          "postcss-nested",
(!) Вот эта часть общая для всех окружений:

```
          [
            "postcss-mixins",
            {
              mixinsFiles: "./src/styles/abstracts/mixins.css",
            },
          ],
          ["postcss-simple-vars", { silent: true }],
          "postcss-nested",
```

и дублировать ее нет смысла. Обычно делают как-то так:

```

const IS_PRODUCTION = process.env.NODE_ENV === "production";

[
  "postcss-mixins",
  "postcss-nested",
  IS_PRODUCTION && "postcss-custom-properties",
  IS_PRODUCTION && "autoprefixer",
].filter(Boolean)
```

Или создают файл common, и отдельный файл для каждого окружения (можно не файлы, а отдельные переменные)

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/components/App/App.tsx
> +      })}
🔥

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/components/Error/Error.css
> +  padding: 3% 0 20px;
Обычно не стоит смешивать пиксели и проценты. Если ширина в px задана, то и паддинг лучше полностью задать в px

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/components/Error/Error.tsx
> +const cnError = cn("error");
Не помню, писал ли я об этом в прошлом ПР, но удобнее такие переменные называть во всех файлах одинаково (например назвать `classname = cn("error");`), это очень упрощает и рефакторинг, и понимание, что содержится в переменной (когда во всех компонентах одно имя). Поэтому советую исправить, но это совсем не критично

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +  render() {
👍

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/components/SettingsForm/SettingsForm.tsx
> +  }, []);
(!) Во всех колбеки с редактом нужно прорастить в зависимости dispatch:
```
  const handleSettingsFormSubmit = useCallback((values: IUserRequest) => {
    dispatch(authOperations.changeUserData(values));
  }, [dispatch]);
```

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/components/SignupForm/SignupForm.tsx
> +  const handleSigninButtonClick = useCallback(() => {
выше используется onSubmit, здесь handleSigninButtonClick. В рамках одного компонента лучше код писать в одном стиле - использовать один глагол для действий (либо on, либо handle

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on webpack.config.js
> +        use: process.env.NODE_ENV === "production" ? "ts-loader" : ["ts-loader", "eslint-loader"],
(!) Что бы везде не использовать  process.env.NODE_ENV === "production", стоит вынести это условие в переменную (IS_PRODUCTION, isProd, isProduction)

2020-10-07 13:39 UTC, noveogroup-amorgunov commented on src/utils/request/__tests__/request.ts
> +    api.post("/endpoint", requestData).reply(200, responseData);
Для тестов запросов очень рекомендую посмотреть на библиотеку nock, которая перехватывает http-запросы. Использовали на нескольких проектах, очень упрощала логику тестов

2020-10-07 16:14 UTC, 0151 commented on src/utils/request/__tests__/request.ts
> +    api.post("/endpoint", requestData).reply(200, responseData);
Тут как раз используется nock)

2020-10-13 07:15 UTC, ShevchenkoAlexen approved these changes

2020-10-15 11:21 UTC, aleksandr-yakovlev approved these changes
Привет! Замечаний нет

2020-10-15 17:35 UTC, merged